version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: eventbridge_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
